export const dados = [
  {
    id: 1,
    vernacular: "Açaizeiro",
    nomecientifico: "Euterpe precatoria",
    autor: "Mart.",
    familia: "Arecaceae",
    codigo: "D23674",
    data_plantio: "12/10/2005",
    coletas: "MELO, LHS 452; HOPKINS, MJG 123",
    descricao:
      "E. precatoria é monocaule de 3 a 23m de altura e de 4 a 23cm de diâmetro, ou raramente cespitoso, palmito fino e liso no topo; tem um cone de raízes visíveis; folhas com pinas planas, de 1 a 3cm de largura, pêndulas ou horizontais; frutos globosos, de cor púrpura-negra quando maduros, com resíduo estigmático lateral; sementes com endosperma homogêneo (Lorenzi et al., 2004; Ferreira, 2005)",
    distribuicao:
      "E. precatoria está distribuída apenas na região Norte, ocupando, predominantemente, o lado Ocidental, nos estados do Amazonas, Acre, Rondônia e Pará, com a variedade longevaginata estando restrita ao Acre, na Serra do Divisor, que faz fronteira com o Peru (Mapa 2) (Henderson; Galeano, 1996; Lorenzi et al., 2004; Flora do Brasil, 2018; Vianna, 2020).",
    distribuicao_mapa: "mapa1.jpg",
    imagelist: ["acai1.jpg", "acai2.jpg", "acai3.jpg", "acai4.jpg"],
  },
  {
    id: 2,
    vernacular: "Fava",
    nomecientifico: "Parkia igneiflora",
    autor: "Ducke",
    familia: "Fabaceae",
    codigo: "D1245",
    data_plantio: "05/04/2000",
    coletas: "HOPKINS, MJG 110",
    descricao: "Sem descrição",
    distribuicao: "Sem descrição",
    distribuicao_mapa: "mapa1.jpg",
    imagelist: ["acai1.jpg", "acai2.jpg", "acai3.jpg", "acai4.jpg"],
  },
  {
    id: 3,
    vernacular: "Mogno",
    nomecientifico: "Swietenia macrophylla",
    autor: "King",
    familia: "Meliaceae",
    codigo: "D23674",
    data_plantio: "03/11/1982",
    coletas: "MELO, LHS 123; MELO, LHS 124",
    descricao: "Sem descrição",
    distribuicao: "Sem descrição",
    distribuicao_mapa: "mapa1.jpg",
    imagelist: ["acai1.jpg", "acai2.jpg", "acai3.jpg", "acai4.jpg"],
  },
];
